{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "bad 0 2\n",
      "good 5 3\n",
      "5\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import numpy.linalg as la\n",
    "\n",
    "template = [0,0,0]\n",
    "first = np.array([1,0,0])\n",
    "second = np.array([0,1,0])\n",
    "third = np.array([0,0,1])\n",
    "blank = np.array([0,0,0])\n",
    "\n",
    "blank_sigma=6\n",
    "#the structure of these disks will be [a_i,...,v_i,sigma_i]\n",
    "#each a_i will be a 3x1 matrix, containing a certain instance of that variable\n",
    "\n",
    "#[a,b,c,e,f|x,y,z,u,v]\n",
    "#[0,1,2,3,4|5,6,7,8,9]\n",
    "\n",
    "#D_1 = a,0,0,e,f,x,0,z,0,v\n",
    "#D_2 = a,b,0,0,f,x,y,0,u,0\n",
    "#D_3 = a,b,c,0,0,0,y,z,0,v\n",
    "#D_4 = 0,b,c,e,0,x,0,z,u,0\n",
    "#D_5 = 0,0,c,e,f,0,y,0,u,v\n",
    "\n",
    "#disk gets updated, it is stored as a vector, containing our information about what disks went into it\n",
    "a=[1,1,1,0,0]\n",
    "b=[0,1,1,1,0]\n",
    "c=[0,0,1,1,1]\n",
    "e=[1,0,0,1,1]\n",
    "f=[1,1,0,0,1]\n",
    "x=[1,1,0,1,0]\n",
    "y=[0,1,1,0,1]\n",
    "z=[1,0,1,1,0]\n",
    "u=[0,1,0,1,1]\n",
    "v=[1,0,1,0,1]\n",
    "\n",
    "var_nums = [a,b,c,e,f,x,y,z,u,v]\n",
    "#now I can get a variable number from this array\n",
    "\n",
    "\n",
    "D=[a,b,c,e,f,x,y,z,u,v]\n",
    "D_1=[]\n",
    "D_2=[]\n",
    "D_3=[]\n",
    "D_4=[]\n",
    "D_5=[]\n",
    "for i in range(len(D)):\n",
    "    var = D[i]\n",
    "    D_1.append(var[0])\n",
    "    D_2.append(var[1])\n",
    "    D_3.append(var[2])\n",
    "    D_4.append(var[3])\n",
    "    D_5.append(var[4])\n",
    "\n",
    "#TO DO\n",
    "#f1=a2+e4+f2+x2+z3+v3\n",
    "#f1=6-(a[1]+e[1]+f[]+x[]+z[]+v[])\n",
    "#f2=b3+f5+a3+y3+u4+x4\n",
    "#f2=6-()\n",
    "#f3=c4+a1+b4+z4+v5+y5\n",
    "#f3=6-()\n",
    "\n",
    "#f4=e5+b2+c5+u5+x1+z1\n",
    "#f4=6-()\n",
    "#f5=f1+c3+e1+v1+y2+u2\n",
    "#f5=6-()\n",
    "\n",
    "D_1 = np.array(D_1)\n",
    "D_2 = np.array(D_2)\n",
    "D_3 = np.array(D_3)\n",
    "D_4 = np.array(D_4)\n",
    "D_5 = np.array(D_5)\n",
    "\n",
    "def or_vector(x,y):\n",
    "    #this takes the OR of two vectors\n",
    "    new = np.empty_like(x)\n",
    "    for i in range(len(x)):\n",
    "        new[i]=x[i]|y[i]\n",
    "    return new\n",
    "\n",
    "\n",
    "def knowledge_of_vars(D_i):\n",
    "    for entry in D_i:\n",
    "        if np.count_nonzero(entry)>0:\n",
    "            entry = np.array([1,1,1])\n",
    "    return D_i\n",
    "\n",
    "\n",
    "def variable_number(D,place,letter):\n",
    "    #this will figure out which number the variable corresponds to - example: the third instance of C is C5\n",
    "    number = 1\n",
    "    temp = 0\n",
    "    toget = 0\n",
    "    index = var_nums.index(letter)\n",
    "    if D_1[index]==1:\n",
    "        if temp<place:\n",
    "            temp+=1\n",
    "        if temp==place:\n",
    "            toget=number\n",
    "    number +=1\n",
    "    if D_2[index]==1:\n",
    "        if temp<place:\n",
    "            temp+=1\n",
    "        if temp==place:\n",
    "            toget=number\n",
    "    number +=1\n",
    "    if D_3[index]==1:\n",
    "        if temp<place:\n",
    "            temp+=1\n",
    "        if temp==place:\n",
    "            toget=number\n",
    "    number +=1\n",
    "    if D_4[index]==1:\n",
    "        if temp<place:\n",
    "            temp+=1\n",
    "        if temp==place:\n",
    "            toget=number\n",
    "    number +=1\n",
    "    if D_5[index]==1:\n",
    "        if temp<place:\n",
    "            temp+=1\n",
    "        if temp==place:\n",
    "            toget=number\n",
    "    number +=1\n",
    "    return toget\n",
    "\n",
    "def eval_vars(D_i):\n",
    "    #this function outputs the amount of information we have on a normal (non-sigma) section of the disk\n",
    "    for entry in D_i:\n",
    "        if np.count_nonzero(entry)==3:\n",
    "            entry = 2\n",
    "        elif np.count_nonzero(entry)==1:\n",
    "            entry=1\n",
    "        else:\n",
    "            entry = 0\n",
    "    return D_i\n",
    "            \n",
    "def eval_sigma(D_i):\n",
    "    #this function outputs the amount of information we have on a sigma section of the disk\n",
    "    #we have to account for all 5 variables of the sigma entry\n",
    "    return D_i\n",
    "            \n",
    "def entropy(disk):\n",
    "    #this will add the information from each entry of the disk\n",
    "    #once we know 20 pieces of information, we know the contents of every disk\n",
    "    entropy = 0\n",
    "    for i in range(len(disk)-1):\n",
    "        entropy+=disk(i)\n",
    "    if entropy>=20:\n",
    "        print(\"You know the entire message!\")\n",
    "    else:\n",
    "        print(f\"You know {entropy} bits of information\")\n",
    "    return entropy\n",
    "\n",
    "# def new_disk(disk1, disk2):\n",
    "#     new = np.empty_like[disk1[0][:]]\n",
    "#     for variable in range(len(disk1)):\n",
    "#         new[variable]=vector_or(disk1[variable],disk2[variable])\n",
    "#     return new_disk\n",
    "\n",
    "# print(new_disk(D_1,D_2))\n",
    "\n",
    "#to-do: make a function that gives the S_{i->j} information. I can do this by using OR on the arrays\n",
    "#       make a function that \n",
    "#       write down each sigma value, use them in the disks\n",
    "\n",
    "#main function will input the starting disks, then run through the entropies one-by-one\n",
    "\n",
    "print(variable_number(D,3,c))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
